# defines the default content repository
content: https://github.com/koraa/helix-test.git

# defines the default code (and static) repository
code: https://github.com/koraa/helix-test.git

# defines the default static root relative to the code repository
staticRoot: /dist/

# defines the directory index file
directoryIndex: index.html
