version: 1
strains:
  default:
    name: bd480003-c813-4276-ae91-ad414d365bc7
    code: "https://github.com/koraa/helix-test.git#master"
    content: "https://github.com/koraa/helix-test.git"
    static: "https://github.com/koraa/helix-test/htdocs"
