version: 1
strains:
  - code:
      protocol: https
      host: github.com
      hostname: github.com
      owner: koraa
      repo: helix-test
      ref: master
    content:
      protocol: https
      host: github.com
      hostname: github.com
      owner: koraa
      repo: helix-test
    static:
      protocol: https
      host: github.com
      hostname: github.com
      owner: koraa
      repo: helix-test
      path: /htdocs
    directoryIndex: index.html
    package: varner/4ff86e243a11abff95225339b1c7d0a9d5d403c6
    name: default
